In [1]:
import numpy as np

In [ ]:
np.set_printoptions(suppress=True) #cleaner printing no scientific notation

1.Scalar,Vector,Matrix & Tensor in Numpy

In [ ]:
# scalar - single number
scalar = 5.0
print(scalar)

5.0


In [4]:
# vector - 1D data
vector = np.array(
    [3, 7, 2]
)
print("Vector:",vector)
print("Shape of vector:", vector.shape)

Vector: [3 7 2]
Shape of vector: (3,)


In [6]:
#matrix
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]

    ]
    
)
print("Matrix:")
print(matrix)
print("Shape of matrix:", matrix.shape)

Matrix:
[[1 2 3]
 [4 5 6]]
Shape of matrix: (2, 3)


In [7]:
# Tensor
tensor = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [11, 12, 13],
            [14, 15, 16]
        ]
    ]
)
print("Tensor:")
print(tensor)
print("Shape of tensor:", tensor.shape)

Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
Shape of tensor: (2, 2, 3)


2.Creating vectors and matrices for ML style data

In [9]:
X = np.array(
    [
        [2, 30],
        [5, 80],
        [1, 20]
    ]
)

y = np.array([0, 1, 0])

print("Data matrix X:\n", X)
print("X shape:", X.shape)

print("Output Vector y:\n", y)
print("y shape:", y.shape)

x1 = X[0]
print("\nFirst sample as a vector:", x1)
print("x1 shape:", x1.shape)

Data matrix X:
 [[ 2 30]
 [ 5 80]
 [ 1 20]]
X shape: (3, 2)
Output Vector y:
 [0 1 0]
y shape: (3,)

First sample as a vector: [ 2 30]
x1 shape: (2,)


3.Basic operations: addition, scalar multiplication, transpose

In [11]:
# Two vectors with same length
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print("v1:", v1)
print("v2:", v2)

# vector addition
v_add = v1 + v2
print("\nVector addition v1 + v2:", v_add)

# scalar multiplication
v1_scaled = 2 * v1
print("Scalar multiplication 2 * v1:", v1_scaled)

v1: [1 2 3]
v2: [4 5 6]

Vector addition v1 + v2: [5 7 9]
Scalar multiplication 2 * v1: [2 4 6]


In [15]:
# matrix
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])
print("\nMatrix A:\n", A)
print("Matrix B:\n", B)

#Matrix Addition
A_add_B = A+B
print("\nMatrix addition A+B:\n", A_add_B)

#Scaled multiplication
A_scaled = 0.5 * A
print("Scalar multiplication 0.5 * A:\n", A_scaled)

# transpose
A_T = A.T
print("\nTranspose of A:\n", A_T)
print("A Shape:", A.shape,"(A.T shape:", A_T.shape)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[10 20]
 [30 40]]

Matrix addition A+B:
 [[11 22]
 [33 44]]
Scalar multiplication 0.5 * A:
 [[0.5 1. ]
 [1.5 2. ]]

Transpose of A:
 [[1 3]
 [2 4]]
A Shape: (2, 2) (A.T shape: (2, 2)
